repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
        exclude: |
            (?x)^(
                .*\.md|
                .*\.mdx
            )$
    -   id: end-of-file-fixer
        exclude: |
            (?x)^(
                .*\.md|
                .*\.mdx
            )$
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-json
    -   id: check-merge-conflict
    -   id: detect-private-key
    -   id: mixed-line-ending
        args: [--fix=lf]
        exclude: |
            (?x)^(
                .*\.md|
                .*\.mdx
            )$

-   repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
    -   id: black
        language_version: python3
        args: [--line-length=88]
        exclude: |
            (?x)^(
                .*\.md
            )$

-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        args: ["--profile", "black", "--filter-files"]
        exclude: |
            (?x)^(
                .*\.md
            )$

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.8.4
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        exclude: |
            (?x)^(
                .*\.md
            )$
    -   id: ruff-format
        args: [--check]
        exclude: |
            (?x)^(
                .*\.md
            )$

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
    -   id: mypy
        additional_dependencies:
        - types-PyYAML
        - types-requests
        - types-python-jose
        args: [--ignore-missing-imports, --install-types, --non-interactive]
        exclude: |
            (?x)^(
                .*\.md
            )$

-   repo: https://github.com/PyCQA/bandit
    rev: 1.8.0
    hooks:
    -   id: bandit
        args: ["-ll", "-i"]
        exclude: |
            (?x)^(
                .*\.md
            )$

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
    -   id: pyupgrade
        args: [--py312-plus]
        exclude: |
            (?x)^(
                .*\.md
            )$

default_language_version:
    python: python3.12

exclude: |
    (?x)^(
        \.git/.*|
        \.venv/.*|
        \.env/.*|
        __pycache__/.*|
        \.pytest_cache/.*|
        \.mypy_cache/.*|
        \.ruff_cache/.*|
        \.coverage.*
    )$
