services:
  app:
    build: .
    ports:
      - "54789:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./.env:/app/.env
      - ./scripts:/app/scripts
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - internal
      - external
    depends_on:
      ollama:
        condition: service_healthy
    tty: true
    stdin_open: true
    entrypoint: ["/bin/sh", "-c"]
    command: |
      set -ex
      echo "Container starting at $(date)..."
      echo "Current directory:"
      pwd
      echo "Directory contents:"
      ls -la
      echo "Environment:"
      env
      echo "Creating directories..."
      mkdir -p /app/data /app/logs
      echo "Starting initialization..."
      chmod +x /app/scripts/init-ollama.sh
      echo "Running init-ollama.sh..."
      bash -x /app/scripts/init-ollama.sh || { echo "Ollama initialization failed with code $?"; exit 1; }
      echo "Starting FastAPI server..."
      exec poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - internal
    environment:
      - GIN_MODE=release
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/version", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
    entrypoint: []
    command: ollama serve

networks:
  internal:
    internal: true
  external:
    internal: false

volumes:
  ollama_data: 