services:
  app:
    build: .
    ports:
      - "54789:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./.env:/app/.env
      - ./scripts:/app/scripts
      - whisper_models:/app/models/whisper
    environment:
      - PYTHONUNBUFFERED=1
      - WHISPER_MODEL_PATH=/app/models/whisper
      - POETRY_VIRTUALENVS_CREATE=false
    networks:
      - internal
      - external
    depends_on:
      ollama:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - internal
    environment:
      - GIN_MODE=release
      - OLLAMA_ORIGINS=*
      - OLLAMA_HOST=0.0.0.0:11434
      - OLLAMA_COMPUTE=cpu
      - GOAMD64=v3
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G
        reservations:
          cpus: '2'
          memory: 4G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/version", "||", "exit", "1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped

networks:
  internal:
    internal: true
  external:
    internal: false

volumes:
  ollama_data:
  whisper_models: 